# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Whop2p < Formula
  desc "Private, read-only torrent metadata catalog browser"
  homepage "https://github.com/techmore/WhoPiratesThePirates"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/techmore/WhoPiratesThePirates/releases/download/v0.1.4/whop2p_0.1.4_darwin_amd64.tar.gz"
      sha256 "f0016c39df4b2cd41d79342f7d0fec44ecb52c43c4e4ae065aefd997e23af9fb"

      define_method(:install) do
        bin.install "whop2p"
        bin.install_symlink "whop2p" => "who-pirates-the-pirates"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/techmore/WhoPiratesThePirates/releases/download/v0.1.4/whop2p_0.1.4_darwin_arm64.tar.gz"
      sha256 "44b70c8390527f7f8216529f2cb53705f7bb4530372d175777b23a9fa0390f2a"

      define_method(:install) do
        bin.install "whop2p"
        bin.install_symlink "whop2p" => "who-pirates-the-pirates"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/techmore/WhoPiratesThePirates/releases/download/v0.1.4/whop2p_0.1.4_linux_amd64.tar.gz"
      sha256 "8ba6816c9a0b63378dc4fc6900147e4fd2786066479e37364712f19b70f4aa2b"
      define_method(:install) do
        bin.install "whop2p"
        bin.install_symlink "whop2p" => "who-pirates-the-pirates"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/techmore/WhoPiratesThePirates/releases/download/v0.1.4/whop2p_0.1.4_linux_arm64.tar.gz"
      sha256 "16ac4f04f040961cad5dec9ef12ddbc0b11c16eae54b5d7a080ebcfe32fe984a"
      define_method(:install) do
        bin.install "whop2p"
        bin.install_symlink "whop2p" => "who-pirates-the-pirates"
      end
    end
  end

  def caveats
    <<~EOS
      Configure APP_DB_PATH, APP_STATE_PATH, and ADMIN_PASSWORD before starting the service.
    EOS
  end

  service do
    run [opt_bin/"whop2p"]
    keep_alive true
    working_dir Pathname(ENV["HOME"])
    log_path "~/Library/Logs/whop2p.log"
  end

  test do
    system "#{bin}/whop2p", "--version"
  end
end
