# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Whop2p < Formula
  desc "Private, read-only torrent metadata catalog browser"
  homepage "https://github.com/techmore/WhoPiratesThePirates"
  version "0.1.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/techmore/WhoPiratesThePirates/releases/download/v0.1.7/whop2p_0.1.7_darwin_amd64.tar.gz"
      sha256 "375ebe19eec454b77ab30c26ac3e6f245a5fc23025a4314dc1103ef5b60432a6"

      define_method(:install) do
        bin.install "whop2p"
        bin.install_symlink "whop2p" => "who-pirates-the-pirates"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/techmore/WhoPiratesThePirates/releases/download/v0.1.7/whop2p_0.1.7_darwin_arm64.tar.gz"
      sha256 "9fc75d496e967c4e437e7a34c8303e65cbc39d72a2f79fd27dcde5965a3551eb"

      define_method(:install) do
        bin.install "whop2p"
        bin.install_symlink "whop2p" => "who-pirates-the-pirates"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/techmore/WhoPiratesThePirates/releases/download/v0.1.7/whop2p_0.1.7_linux_amd64.tar.gz"
      sha256 "2c5584f3dac9d513066960753c168e8fc11a96a37be202b1f3c70132c0e509a3"
      define_method(:install) do
        bin.install "whop2p"
        bin.install_symlink "whop2p" => "who-pirates-the-pirates"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/techmore/WhoPiratesThePirates/releases/download/v0.1.7/whop2p_0.1.7_linux_arm64.tar.gz"
      sha256 "9d2da8790e2539829e280cc021d33c101c11e4ebdc14012e096c165c17271bb6"
      define_method(:install) do
        bin.install "whop2p"
        bin.install_symlink "whop2p" => "who-pirates-the-pirates"
      end
    end
  end

  def caveats
    <<~EOS
      Configure APP_DB_PATH, APP_STATE_PATH, and ADMIN_PASSWORD before starting the service.
    EOS
  end

  service do
    run [opt_bin/"whop2p"]
    keep_alive true
    working_dir Pathname(ENV["HOME"])
    log_path "~/Library/Logs/whop2p.log"
  end

  test do
    system "#{bin}/whop2p", "--version"
  end
end
