# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Whop2p < Formula
  desc "Private, read-only torrent metadata catalog browser"
  homepage "https://github.com/techmore/WhoPiratesThePirates"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/techmore/WhoPiratesThePirates/releases/download/v0.1.3/whop2p_0.1.3_darwin_amd64.tar.gz"
      sha256 "3776ee737091561104b624f48bce3ddb09091d061b12e27cd3f946da011865dc"

      define_method(:install) do
        bin.install "whop2p"
        bin.install_symlink "whop2p" => "who-pirates-the-pirates"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/techmore/WhoPiratesThePirates/releases/download/v0.1.3/whop2p_0.1.3_darwin_arm64.tar.gz"
      sha256 "c374d9cdc882a75b26c465d92db781131c0c431060ce47aa8899eace7209c1fc"

      define_method(:install) do
        bin.install "whop2p"
        bin.install_symlink "whop2p" => "who-pirates-the-pirates"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/techmore/WhoPiratesThePirates/releases/download/v0.1.3/whop2p_0.1.3_linux_amd64.tar.gz"
      sha256 "e187ba59a465b39fa5cbe28806980e3a158d91ef054990362ca6438c7186736e"
      define_method(:install) do
        bin.install "whop2p"
        bin.install_symlink "whop2p" => "who-pirates-the-pirates"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/techmore/WhoPiratesThePirates/releases/download/v0.1.3/whop2p_0.1.3_linux_arm64.tar.gz"
      sha256 "4c1fd9c796c4280011bcf00190bb692efff307815693018caa85c3a2e9bb57dd"
      define_method(:install) do
        bin.install "whop2p"
        bin.install_symlink "whop2p" => "who-pirates-the-pirates"
      end
    end
  end

  def caveats
    <<~EOS
      Configure APP_DB_PATH, APP_STATE_PATH, and ADMIN_PASSWORD before starting the service.
    EOS
  end

  service do
    run [opt_bin/"whop2p"]
    keep_alive true
    working_dir Pathname(ENV["HOME"])
    log_path "~/Library/Logs/whop2p.log"
  end

  test do
    system "#{bin}/whop2p", "--version"
  end
end
